import bcrypt from 'bcryptjs';
import { randomBytes } from 'crypto';
import { appendFileSync, existsSync } from 'fs';
import { join } from 'path';
import * as readline from 'readline/promises';

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
});

async function main() {
  console.log('🔐 InterviewVault - Password Setup\n');

  const password = await rl.question('Enter master password: ');
  const confirmPassword = await rl.question('Confirm password: ');

  if (password !== confirmPassword) {
    console.error('❌ Passwords do not match');
    rl.close();
    process.exit(1);
  }

  if (password.length < 8) {
    console.error('❌ Password must be at least 8 characters');
    rl.close();
    process.exit(1);
  }

  console.log('\n⏳ Generating secure hash...');
  const hash = await bcrypt.hash(password, 12);
  const jwtSecret = randomBytes(32).toString('hex');

  const envPath = join(process.cwd(), '.env.local');
  const envExists = existsSync(envPath);

  const envContent = `
# Auto-generated by setup-password.ts
MASTER_PASSWORD_HASH="${hash}"
JWT_SECRET="${jwtSecret}"
MASTER_EMAIL="user@example.com"
MASTER_NAME="Your Name"
# SQLite path is relative to the prisma/ directory (where schema.prisma lives)
DATABASE_URL="file:./dev.db"
# Change this before deploying — anyone registering needs this exact code
INVITE_CODE="change-me-before-deploy"
`;

  if (envExists) {
    console.log('\n⚠️  .env.local already exists. Append anyway? (y/n)');
    const answer = await rl.question('> ');
    if (answer.toLowerCase() !== 'y') {
      console.log('Aborted.');
      rl.close();
      process.exit(0);
    }
  }

  appendFileSync(envPath, envContent);
  console.log('\n✅ Password hash and JWT secret written to .env.local');
  console.log('🔒 Keep this file secure and never commit it to git!');
  console.log('\n💡 You can now update MASTER_EMAIL and MASTER_NAME in .env.local\n');

  rl.close();
}

main().catch((error) => {
  console.error('Error:', error);
  rl.close();
  process.exit(1);
});
